# HW3: Part II - Web Scraping Billboard Music Charts - SOLUTIONS

The Billboard Hot 100 is the music industry standard record chart in the United States for singles, published weekly by Billboard magazine. Chart rankings are based on sales (physical and digital), radio play, and online streaming.  These rankings are used to determine the top singles each year, which can be accessed on Wikipedia.

In this part of the homework you will perform some web scraping of this data. We introduced the Beautiful Soup library in class and how we can use it to extract data from HTML.  Recall that developer tools within Chrome (or simlar tools in other browsers) allows us to view the HTML that makes up a web page.

For additional reference on the Beautiful Soup Library, see Toolbox 11.1 on pg 519 in *Python for Everyone* (pg 643 in 2nd edition).

### Instructions:
* Type your **code** below each question that follows and show the output.  Some code is already provided for you.
* Use **markdown** cells to help organize and explain what you are doing.
* Rename this file by replacing the word "Blank" in the filename with your last name.

## Part 1: Making a Beautiful Soup Object

We will use the year 1997 as an example of scraping data from the Billboard year-end hot 100 singles Wikipedia paage.

In [1]:
import requests
from bs4 import BeautifulSoup
from IPython.display import Image
BASE_URL = "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_"

headers = {
            "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/115.0.0.0 Safari/537.36"
    ),
}

def get_soup(year):
    url = BASE_URL + str(year)
    page = requests.get(url,headers=headers)
    soup = BeautifulSoup(page.content, 'html.parser')
    return soup

year = 1997
soup = get_soup(year)
soup

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Billboard Year-End Hot 100 singles of 1997 - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"2544c157-0e77-468a-baa8-b41acaa71250","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Billboard_Year-End_Hot_100_singles_of_1997","wgTitle":"Billboard Year-End Hot 100 singles of 1997","wgCurRevisionId":1359800231,"wgRevisionId":1359800231,"wgArticleId":19096399,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","1997 record charts","Lists of Billboard Year-End Hot 100 singles","1997 in American music"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Billboard_Year-End_Hot_100_singles_of_1997","wgRelevantArticleId":19096399,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":10000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Project-independent assessment":{"class":"List","importance":""},"Record Charts":{"class":"List","importance":"Low"},"Songs":{"class":"List","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q745193","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.18" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/d/d3/Elton_John_with_Luciano_Pavarotti_in_Modena_1996_%282%29.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail_unscaled" property="og:image"/>
<meta content="911" property="og:image:width"/>
<meta content="1200" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="Billboard Year-End Hot 100 singles of 1997 - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//thumb.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=Billboard_Year-End_Hot_100_singles_of_1997&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1997" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Billboard_Year-End_Hot_100_singles_of_1997 rootpage-Billboard_Year-End_Hot_100_singles_of_1997 skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Billboard+Year-End+Hot+100+singles+of+1997" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=Billboard+Year-End+Hot+100+singles+of+1997" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart cdx-button__icon"></span>
<span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Billboard+Year-End+Hot+100+singles+of+1997" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span>Create account</span></a>
</li>

## Part 2: Store the chart data in a list of dictionaries

The end goal of this part is to make a list called `music_table`.  The list will contain 100 dictionaries, where each dictionary is of the form:

`{song: song_name, artist: [name1, name2, ...], artistURL: [url1, url2, ...], rank: int, year: int}`

That is, each row in the original music data chart will be convereted to a dictionary with five keys:
* The `song` key holds a string (song name),
* the `artist` key holds a list of strings (artist names), 
* the `artistURL` holds a list of strings (urls), 
* the `rank` key holds an int (rank of song), and 
* the `year` key holds the year as in int (in this case they will all be 1997).

In the end, you should have a list of dictionaries that looks like the below.

`[{'artist': ['Elton John'],
  'artistURL': ['/wiki/Elton_John'],
  'rank': 1,
  'song': '"Something About the Way You Look Tonight" / "Candle in the Wind 1997"',
  'year': 1997},
 {'artist': ['Jewel'],
  'artistURL': ['/wiki/Jewel_(singer)'],
  'rank': 2,
  'song': '"Foolish Games" / "You Were Meant for Me"',
  'year': 1997},
 {'artist': ['Puff Daddy', 'Faith Evans', '112'],
  'artistURL': ['/wiki/Sean_Combs', '/wiki/Faith_Evans', '/wiki/112_(band)'],
  'rank': 3,
  'song': '"I\'ll Be Missing You"',
  'year': 1997}
  ...]`

**Hints**:
* the chart data is in a **table** element with class "wikitable"
* each row of data is an html data row (think: "tr" html tag)
* within the row, the data you need for your dictionary can be found inside a **"td"** tag and an **"a"** tag within a **"td"** tag
* the `find_all` function is often useful on Beautiful Soup objects
* to extract urls, find `a`tags then extract using dictionary-indexing with key `href` or else use `.attrs['href']` on them
* if a song has multiple artists and/or links and you are having trouble recording each one into your dictionary, just record the first one in the list
* you might find it easier to break tasks up into functions in Part 2; then you can call them in Part 3; note there already is a get_soup function above that you can use
* occassionally, an artist will span 2 rows - see songs ranked 49 and 50 in 1997; you will need to write code to catch and address this; that row will have 2 items in it instead of 3 (rank and song title, but not artist)

### Some prep work

In [29]:
soup.find("table",class_="wikitable")

<table class="wikitable sortable" id="mwhw" style="text-align: center">
<caption id="mwiA">List of songs on <i id="mwiQ"><a href="https://en.wikipedia.org/wiki/Billboard_(magazine)" id="mwig" rel="mw:WikiLink" title="Billboard (magazine)">Billboard</a></i><span about="#mwt14" class="nowrap" data-mw="{&quot;parts&quot;:[{&quot;template&quot;:{&quot;target&quot;:{&quot;wt&quot;:&quot;'s&quot;,&quot;href&quot;:&quot;./Template:'s&quot;},&quot;params&quot;:{},&quot;i&quot;:0}}]}" id="mwiw" style="padding-left:0.1em;" typeof="mw:Transclusion"><span typeof="mw:Entity">'</span>s</span> 2021 <a href="https://en.wikipedia.org/wiki/Billboard_Year-End" id="mwjA" rel="mw:WikiLink" title="Billboard Year-End">Year-End</a> <a href="https://en.wikipedia.org/wiki/Billboard_Hot_100" id="mwjQ" rel="mw:WikiLink" title="Billboard Hot 100">Hot 100</a> chart<sup about="#mwt17" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-4"}}' id="cite_ref-4" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-4" id="mwjg"><span class="mw-reflink-text" id="mwjw"><span class="cite-bracket" id="mwkA">[</span>4<span class="cite-bracket" id="mwkQ">]</span></span></a></sup></caption>
<tbody id="mwkg"><tr id="mwkw">
<th id="mwlA" scope="col" style="background:#dde;"><abbr about="#mwt18" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwlQ\"&gt;Number&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Abbr","href":"./Template:Abbr"},"params":{"1":{"wt":"No."},"2":{"wt":"Number"}},"i":0}}]}' id="mwlg" title="Number" typeof="mw:Transclusion mw:ExpandedAttrs">No.</abbr></th>
<th id="mwlw" scope="col" style="background:#dde;">Title</th>
<th id="mwmA" scope="col" style="background:#dde;">Artist(s)</th></tr>
<tr id="mwmQ">
<td id="mwmg" scope="row">1</td>
<td id="mwmw">"<a href="https://en.wikipedia.org/wiki/Levitating_(song)" id="mwnA" rel="mw:WikiLink" title="Levitating (song)">Levitating</a>"</td><td id="mwnQ"><a href="https://en.wikipedia.org/wiki/Dua_Lipa" id="mwng" rel="mw:WikiLink" title="Dua Lipa">Dua Lipa</a><!-- Please do not insert "featuring DaBaby" without another reliable source to support that, and/or talk page discussion; the absence of that credit is evident in Billboard's year&#x2D;end chart and solely their decision, even though the featuring credit was that way for the majority of 2021 on their weekly lists --></td></tr>
<tr id="mwnw">
<td id="mwoA" scope="row">2</td>
<td id="mwoQ">"<a href="https://en.wikipedia.org/wiki/Save_Your_Tears" id="mwog" rel="mw:WikiLink" title="Save Your Tears">Save Your Tears</a>"</td><td id="mwow"><a href="https://en.wikipedia.org/wiki/The_Weeknd" id="mwpA" rel="mw:WikiLink" title="The Weeknd">The Weeknd</a> and <a href="https://en.wikipedia.org/wiki/Ariana_Grande" id="mwpQ" rel="mw:WikiLink" title="Ariana Grande">Ariana Grande</a></td></tr>
<tr id="mwpg">
<td id="mwpw" scope="row">3</td>
<td id="mwqA">"<a href="https://en.wikipedia.org/wiki/Blinding_Lights" id="mwqQ" rel="mw:WikiLink" title="Blinding Lights">Blinding Lights</a>"</td><td id="mwqg"><a href="https://en.wikipedia.org/wiki/The_Weeknd" id="mwqw" rel="mw:WikiLink" title="The Weeknd">The Weeknd</a></td></tr>
<tr id="mwrA">
<td id="mwrQ" scope="row">4</td>
<td id="mwrg">"<a href="https://en.wikipedia.org/wiki/Mood_(24kGoldn_song)" id="mwrw" rel="mw:WikiLink" title="Mood (24kGoldn song)">Mood</a>"</td><td id="mwsA"><a href="https://en.wikipedia.org/wiki/24kGoldn" id="mwsQ" rel="mw:WikiLink" title="24kGoldn">24kGoldn</a> featuring <a href="https://en.wikipedia.org/wiki/Iann_Dior" id="mwsg" rel="mw:WikiLink" title="Iann Dior">Iann Dior</a></td></tr>
<tr id="mwsw">
<td id="mwtA" scope="row">5</td>
<td id="mwtQ">"<a href="https://en.wikipedia.org/wiki/Good_4_U" id="mwtg" rel="mw:WikiLink" title="Good 4 U">Good 4 U</a>"</td><td id="mwtw"><a href="https://en.wikipedia.org/wiki/Olivia_Rodrigo" id="mwuA" rel="mw:WikiLink" title="Olivia Rodrigo">Olivia Rodrigo</a></td></tr>
<tr id="mwuQ">
<td id="mwug" scope="row">6</td>
<td id="mwuw">"<a href="https://en.wikipedia.org/wiki/Kiss_Me_More" id="mwvA" rel="mw:WikiLink" title="Kiss Me More">Kiss Me More</a>"</td><td id="mwvQ"><a href="https://en.wikipedia.org/wiki/Doja_Cat" id="mwvg" rel="mw:WikiLink" title="Doja Cat">Doja Cat</a> featuring <a href="https://en.wikipedia.org/wiki/SZA" id="mwvw" rel="mw:WikiLink" title="SZA">SZA</a></td></tr>
<tr id="mwwA">
<td id="mwwQ" scope="row">7</td>
<td id="mwwg">"<a href="https://en.wikipedia.org/wiki/Leave_the_Door_Open" id="mwww" rel="mw:WikiLink" title="Leave the Door Open">Leave the Door Open</a>"</td><td id="mwxA"><a href="https://en.wikipedia.org/wiki/Silk_Sonic" id="mwxQ" rel="mw:WikiLink" title="Silk Sonic">Silk Sonic</a> (<a href="https://en.wikipedia.org/wiki/Bruno_Mars" id="mwxg" rel="mw:WikiLink" title="Bruno Mars">Bruno Mars</a> and <a href="https://en.wikipedia.org/wiki/Anderson_.Paak" id="mwxw" rel="mw:WikiLink" title="Anderson .Paak">Anderson .Paak</a>)</td></tr>
<tr id="mwyA">
<td id="mwyQ" scope="row">8</td>
<td id="mwyg">"<a href="https://en.wikipedia.org/wiki/Drivers_License_(song)" id="mwyw" rel="mw:WikiLink" title="Drivers License (song)">Drivers License</a>"</td><td id="mwzA"><a href="https://en.wikipedia.org/wiki/Olivia_Rodrigo" id="mwzQ" rel="mw:WikiLink" title="Olivia Rodrigo">Olivia Rodrigo</a></td></tr>
<tr id="mwzg">
<td id="mwzw" scope="row">9</td>
<td id="mw0A">"<a href="https://en.wikipedia.org/wiki/Montero_(Call_Me_by_Your_Name)" id="mw0Q" rel="mw:WikiLink" title="Montero (Call Me by Your Name)">Montero (Call Me by Your Name)</a>"</td><td id="mw0g"><a href="https://en.wikipedia.org/wiki/Lil_Nas_X" id="mw0w" rel="mw:WikiLink" title="Lil Nas X">Lil Nas X</a></td></tr>
<tr id="mw1A">
<td id="mw1Q" scope="row">10</td>
<td id="mw1g">"<a href="https://en.wikipedia.org/wiki/Peaches_(Justin_Bieber_song)" id="mw1w" rel="mw:WikiLink" title="Peaches (Justin Bieber song)">Peaches</a>"</td><td id="mw2A"><a href="https://en.wikipedia.org/wiki/Justin_Bieber" id="mw2Q" rel="mw:WikiLink" title="Justin Bieber">Justin Bieber</a> featuring <a href="https://en.wikipedia.org/wiki/Daniel_Caesar" id="mw2g" rel="mw:WikiLink" title="Daniel Caesar">Daniel Caesar</a> and <a href="https://en.wikipedia.org/wiki/Giveon" id="mw2w" rel="mw:WikiLink" title="Giveon">Giveon</a></td></tr>
<tr id="mw3A">
<td id="mw3Q" scope="row">11</td>
<td id="mw3g">"<a href="https://en.wikipedia.org/wiki/Butter_(song)" id="mw3w" rel="mw:WikiLink" title="Butter (song)">Butter</a>"</td><td id="mw4A"><a href="https://en.wikipedia.org/wiki/BTS" id="mw4Q" rel="mw:WikiLink" title="BTS">BTS</a></td></tr>
<tr id="mw4g">
<td id="mw4w" scope="row">12</td>
<td id="mw5A">"<a href="https://en.wikipedia.org/wiki/Stay_(The_Kid_Laroi_and_Justin_Bieber_song)" id="mw5Q" rel="mw:WikiLink" title="Stay (The Kid Laroi and Justin Bieber song)">Stay</a>"</td><td id="mw5g"><a href="https://en.wikipedia.org/wiki/The_Kid_Laroi" id="mw5w" rel="mw:WikiLink" title="The Kid Laroi">The Kid Laroi</a> and <a href="https://en.wikipedia.org/wiki/Justin_Bieber" id="mw6A" rel="mw:WikiLink" title="Justin Bieber">Justin Bieber</a></td></tr>
<tr id="mw6Q">
<td id="mw6g" scope="row">13</td>
<td id="mw6w">"<a href="https://en.wikipedia.org/wiki/Deja_Vu_(Olivia_Rodrigo_song)" id="mw7A" rel="mw:WikiLink" title="Deja Vu (Olivia Rodrigo song)">Deja Vu</a>"</td><td id="mw7Q"><a href="https://en.wikipedia.org/wiki/Olivia_Rodrigo" id="mw7g" rel="mw:WikiLink" title="Olivia Rodrigo">Olivia Rodrigo</a></td></tr>
<tr id="mw7w">
<td id="mw8A" scope="row">14</td>
<td id="mw8Q">"<a href="https://en.wikipedia.org/wiki/Positions_(song)" id="mw8g" rel="mw:WikiLink" title="Positions (song)">Positions</a>"</td><td id="mw8w"><a href="https://en.wikipedia.org/wiki/Ariana_Grande" id="mw9A" rel="mw:WikiLink" title="Ariana Grande">Ariana Grande</a></td></tr>
<tr id="mw9Q">
<td id="mw9g" scope="row">15</td>
<td id="mw9w">"<a href="https://en.wikipedia.org/wiki/Bad_Habits_(Ed_Sheeran_song)" id="mw-A" rel="mw:WikiLink" title="Bad Habits (Ed Sheeran song)">Bad Habits</a>"</td><td id="mw-Q"><a href="https://en.wikipedia.org/wiki/Ed_Sheeran" id="mw-g" rel="mw:WikiLink" title="Ed Sheeran">Ed Sheeran</a></td></tr>
<tr id="mw-w">
<td id="mw_A" scope="row">16</td>
<td id="mw_Q">"<a href="https://en.wikipedia.org/wiki/Heat_Waves" id="mw_g" rel="mw:WikiLink" title="Heat Waves">Heat Waves</a>"</td><td id="mw_w"><a href="https://en.wikipedia.org/wiki/Glass_Animals" id="mwAQA" rel="mw:WikiLink" title="Glass Animals">Glass Animals</a></td></tr>
<tr id="mwAQE">
<td id="mwAQI" scope="row">17</td>
<td id="mwAQM">"<a href="https://en.wikipedia.org/wiki/Without_You_(The_Kid_Laroi_song)" id="mwAQQ" rel="mw:WikiLink" title="Without You (The Kid Laroi song)">Without You</a>"</td><td id="mwAQU"><a href="https://en.wikipedia.org/wiki/The_Kid_Laroi" id="mwAQY" rel="mw:WikiLink" title="The Kid Laroi">The Kid Laroi</a></td></tr>
<tr id="mwAQc">
<td id="mwAQg" scope="row">18</td>
<td id="mwAQk">"<a href="https://en.wikipedia.org/wiki/Forever_After_All" id="mwAQo" rel="mw:WikiLink" title="Forever After All">Forever After All</a>"</td><td id="mwAQs"><a href="https://en.wikipedia.org/wiki/Luke_Combs" id="mwAQw" rel="mw:WikiLink" title="Luke Combs">Luke Combs</a></td></tr>
<tr id="mwAQ0">
<td id="mwAQ4" scope="row">19</td>
<td id="mwAQ8">"<a href="https://en.wikipedia.org/wiki/Go_Crazy_(Chris_Brown_and_Young_Thug_song)" id="mwARA" rel="mw:WikiLink" title="Go Crazy (Chris Brown and Young Thug song)">Go Crazy</a>"</td><td id="mwARE"><a href="https://en.wikipedia.org/wiki/Chris_Brown" id="mwARI" rel="mw:WikiLink" title="Chris Brown">Chris Brown</a> and <a href="https://en.wikipedia.org/wiki/Young_Thug" id="mwARM" rel="mw:WikiLink" title="Young Thug">Young Thug</a></td></tr>
<tr id="mwARQ">
<td id="mwARU" scope="row">20</td>
<td id="mwARY">"<a href="https://en.wikipedia.org/wiki/Astronaut_in_the_Ocean" id="mwARc" rel="mw:WikiLink" title="Astronaut in the Ocean">Astronaut in the Ocean</a>"</td><td id="mwARg"><a href="https://en.wikipedia.org/wiki/Masked_Wolf" id="mwARk" rel="mw:WikiLink" title="Masked Wolf">Masked Wolf</a></td></tr>
<tr id="mwARo">
<td id="mwARs" scope="row">21</td>
<td id="mwARw">"<a href="https://en.wikipedia.org/wiki/34+35" id="mwAR0" rel="mw:WikiLink" title="34+35">34+35</a>"</td><td id="mwAR4"><a href="https://en.wikipedia.org/wiki/Ariana_Grande" id="mwAR8" rel="mw:WikiLink" title="Ariana Grande">Ariana Grande</a> featuring <a href="https://en.wikipedia.org/wiki/Doja_Cat" id="mwASA" rel="mw:WikiLink" title="Doja Cat">Doja Cat</a> and <a href="https://en.wikipedia.org/wiki/Megan_Thee_Stallion" id="mwASE" rel="mw:WikiLink" title="Megan Thee Stallion">Megan Thee Stallion</a></td></tr>
<tr id="mwASI">
<td id="mwASM" scope="row">22</td>
<td id="mwASQ">"<a href="https://en.wikipedia.org/wiki/What_You_Know_Bout_Love" id="mwASU" rel="mw:WikiLink" title="What You Know Bout Love">What You Know Bout Love</a>"</td><td id="mwASY"><a href="https://en.wikipedia.org/wiki/Pop_Smoke" id="mwASc" rel="mw:WikiLink" title="Pop Smoke">Pop Smoke</a></td></tr>
<tr id="mwASg">
<td id="mwASk" scope="row">23</td>
<td id="mwASo">"<a href="https://en.wikipedia.org/wiki/My_Ex's_Best_Friend" id="mwASs" rel="mw:WikiLink" title="My Ex's Best Friend">My Ex's Best Friend</a>"</td><td id="mwASw"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Machine_Gun_Kelly_(musician)" id="mwAS0" rel="mw:WikiLink" title="Machine Gun Kelly (musician)">Machine Gun Kelly</a> featuring <a href="https://en.wikipedia.org/wiki/Blackbear_(musician)" id="mwAS4" rel="mw:WikiLink" title="Blackbear (musician)">Blackbear</a></td></tr>
<tr id="mwAS8">
<td id="mwATA" scope="row">24</td>
<td id="mwATE">"<a href="https://en.wikipedia.org/wiki/Industry_Baby" id="mwATI" rel="mw:WikiLink" title="Industry Baby">Industry Baby</a>"</td><td id="mwATM"><a href="https://en.wikipedia.org/wiki/Lil_Nas_X" id="mwATQ" rel="mw:WikiLink" title="Lil Nas X">Lil Nas X</a> and <a href="https://en.wikipedia.org/wiki/Jack_Harlow" id="mwATU" rel="mw:WikiLink" title="Jack Harlow">Jack Harlow</a></td></tr>
<tr id="mwATY">
<td id="mwATc" scope="row">25</td>
<td id="mwATg">"<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Therefore_I_Am_(Billie_Eilish_song)" id="mwATk" rel="mw:WikiLink" title="Therefore I Am (Billie Eilish song)">Therefore I Am</a>"</td><td id="mwATo"><a href="https://en.wikipedia.org/wiki/Billie_Eilish" id="mwATs" rel="mw:WikiLink" title="Billie Eilish">Billie Eilish</a></td></tr>
<tr id="mwATw">
<td id="mwAT0" scope="row">26</td>
<td id="mwAT4">"<a href="https://en.wikipedia.org/wiki/Up_(Cardi_B_song)" id="mwAT8" rel="mw:WikiLink" title="Up (Cardi B song)">Up</a>"</td><td id="mwAUA"><a href="https://en.wikipedia.org/wiki/Cardi_B" id="mwAUE" rel="mw:WikiLink" title="Cardi B">Cardi B</a></td></tr>
<tr id="mwAUI">
<td id="mwAUM" scope="row">27</td>
<td id="mwAUQ">"<a href="https://en.wikipedia.org/wiki/Fancy_Like" id="mwAUU" rel="mw:WikiLink" title="Fancy Like">Fancy Like</a>"</td><td id="mwAUY"><a href="https://en.wikipedia.org/wiki/Walker_Hayes" id="mwAUc" rel="mw:WikiLink" title="Walker Hayes">Walker Hayes</a></td></tr>
<tr id="mwAUg">
<td id="mwAUk" scope="row">28</td>
<td id="mwAUo">"<a href="https://en.wikipedia.org/wiki/Dakiti" id="mwAUs" rel="mw:WikiLink" title="Dakiti">Dakiti</a>"</td><td id="mwAUw"><a href="https://en.wikipedia.org/wiki/Bad_Bunny" id="mwAU0" rel="mw:WikiLink" title="Bad Bunny">Bad Bunny</a> and <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Jhay_Cortez" id="mwAU4" rel="mw:WikiLink" title="Jhay Cortez">Jhay Cortez</a></td></tr>
<tr id="mwAU8">
<td id="mwAVA" scope="row">29</td>
<td id="mwAVE">"<a href="https://en.wikipedia.org/wiki/Best_Friend_(Saweetie_song)" id="mwAVI" rel="mw:WikiLink" title="Best Friend (Saweetie song)">Best Friend</a>"</td><td id="mwAVM"><a href="https://en.wikipedia.org/wiki/Saweetie" id="mwAVQ" rel="mw:WikiLink" title="Saweetie">Saweetie</a> featuring <a href="https://en.wikipedia.org/wiki/Doja_Cat" id="mwAVU" rel="mw:WikiLink" title="Doja Cat">Doja Cat</a></td></tr>
<tr id="mwAVY">
<td id="mwAVc" scope="row">30</td>
<td id="mwAVg">"<a href="https://en.wikipedia.org/wiki/Rapstar" id="mwAVk" rel="mw:WikiLink" title="Rapstar">Rapstar</a>"</td><td id="mwAVo"><a href="https://en.wikipedia.org/wiki/Polo_G" id="mwAVs" rel="mw:WikiLink" title="Polo G">Polo G</a></td></tr>
<tr id="mwAVw">
<td id="mwAV0" scope="row">31</td>
<td id="mwAV4">"<a href="https://en.wikipedia.org/wiki/Heartbreak_Anniversary" id="mwAV8" rel="mw:WikiLink" title="Heartbreak Anniversary">Heartbreak Anniversary</a>"</td><td id="mwAWA"><a href="https://en.wikipedia.org/wiki/Giveon" id="mwAWE" rel="mw:WikiLink" title="Giveon">Giveon</a></td></tr>
<tr id="mwAWI">
<td id="mwAWM" scope="row">32</td>
<td id="mwAWQ">"<a href="https://en.wikipedia.org/wiki/For_the_Night" id="mwAWU" rel="mw:WikiLink" title="For the Night">For the Night</a>"</td><td id="mwAWY"><a href="https://en.wikipedia.org/wiki/Pop_Smoke" id="mwAWc" rel="mw:WikiLink" title="Pop Smoke">Pop Smoke</a> featuring <a href="https://en.wikipedia.org/wiki/Lil_Baby" id="mwAWg" rel="mw:WikiLink" title="Lil Baby">Lil Baby</a> and <a href="https://en.wikipedia.org/wiki/DaBaby" id="mwAWk" rel="mw:WikiLink" title="DaBaby">DaBaby</a></td></tr>
<tr id="mwAWo">
<td id="mwAWs" scope="row">33</td>
<td id="mwAWw">"<a href="https://en.wikipedia.org/wiki/Calling_My_Phone" id="mwAW0" rel="mw:WikiLink" title="Calling My Phone">Calling My Phone</a>"</td><td id="mwAW4"><a href="https://en.wikipedia.org/wiki/Lil_Tjay" id="mwAW8" rel="mw:WikiLink" title="Lil Tjay">Lil Tjay</a> and <a href="https://en.wikipedia.org/wiki/6lack" id="mwAXA" rel="mw:WikiLink" title="6lack">6lack</a></td></tr>
<tr id="mwAXE">
<td id="mwAXI" scope="row">34</td>
<td id="mwAXM">"<a href="https://en.wikipedia.org/wiki/Beautiful_Mistakes" id="mwAXQ" rel="mw:WikiLink" title="Beautiful Mistakes">Beautiful Mistakes</a>"</td><td id="mwAXU"><a href="https://en.wikipedia.org/wiki/Maroon_5" id="mwAXY" rel="mw:WikiLink" title="Maroon 5">Maroon 5</a> featuring <a href="https://en.wikipedia.org/wiki/Megan_Thee_Stallion" id="mwAXc" rel="mw:WikiLink" title="Megan Thee Stallion">Megan Thee Stallion</a></td></tr>
<tr id="mwAXg">
<td id="mwAXk" scope="row">35</td>
<td id="mwAXo">"<a href="https://en.wikipedia.org/wiki/Holy_(Justin_Bieber_song)" id="mwAXs" rel="mw:WikiLink" title="Holy (Justin Bieber song)">Holy</a>"</td><td id="mwAXw"><a href="https://en.wikipedia.org/wiki/Justin_Bieber" id="mwAX0" rel="mw:WikiLink" title="Justin Bieber">Justin Bieber</a> featuring <a href="https://en.wikipedia.org/wiki/Chance_the_Rapper" id="mwAX4" rel="mw:WikiLink" title="Chance the Rapper">Chance the Rapper</a></td></tr>
<tr id="mwAX8">
<td id="mwAYA" scope="row">36</td>
<td id="mwAYE">"<a href="https://en.wikipedia.org/wiki/On_Me_(Lil_Baby_song)" id="mwAYI" rel="mw:WikiLink" title="On Me (Lil Baby song)">On Me</a>"</td><td id="mwAYM"><a href="https://en.wikipedia.org/wiki/Lil_Baby" id="mwAYQ" rel="mw:WikiLink" title="Lil Baby">Lil Baby</a></td></tr>
<tr id="mwAYU">
<td id="mwAYY" scope="row">37</td>
<td id="mwAYc">"<a href="https://en.wikipedia.org/wiki/You_Broke_Me_First" id="mwAYg" rel="mw:WikiLink" title="You Broke Me First">You Broke Me First</a>"</td><td id="mwAYk"><a href="https://en.wikipedia.org/wiki/Tate_McRae" id="mwAYo" rel="mw:WikiLink" title="Tate McRae">Tate McRae</a></td></tr>
<tr id="mwAYs">
<td id="mwAYw" scope="row">38</td>
<td id="mwAY0">"<a href="https://en.wikipedia.org/wiki/Traitor_(song)" id="mwAY4" rel="mw:WikiLink" title="Traitor (song)">Traitor</a>"</td><td id="mwAY8"><a href="https://en.wikipedia.org/wiki/Olivia_Rodrigo" id="mwAZA" rel="mw:WikiLink" title="Olivia Rodrigo">Olivia Rodrigo</a></td></tr>
<tr id="mwAZE">
<td id="mwAZI" scope="row">39</td>
<td id="mwAZM">"<a href="https://en.wikipedia.org/wiki/Back_in_Blood_(song)" id="mwAZQ" rel="mw:WikiLink" title="Back in Blood (song)">Back in Blood</a>"</td><td id="mwAZU"><a href="https://en.wikipedia.org/wiki/Pooh_Shiesty" id="mwAZY" rel="mw:WikiLink" title="Pooh Shiesty">Pooh Shiesty</a> featuring <a href="https://en.wikipedia.org/wiki/Lil_Durk" id="mwAZc" rel="mw:WikiLink" title="Lil Durk">Lil Durk</a></td></tr>
<tr id="mwAZg">
<td id="mwAZk" scope="row">40</td>
<td id="mwAZo">"<a href="https://en.wikipedia.org/wiki/I_Hope_(Gabby_Barrett_song)" id="mwAZs" rel="mw:WikiLink" title="I Hope (Gabby Barrett song)">I Hope</a>"</td><td id="mwAZw"><a href="https://en.wikipedia.org/wiki/Gabby_Barrett" id="mwAZ0" rel="mw:WikiLink" title="Gabby Barrett">Gabby Barrett</a> featuring <a href="https://en.wikipedia.org/wiki/Charlie_Puth" id="mwAZ4" rel="mw:WikiLink" title="Charlie Puth">Charlie Puth</a></td></tr>
<tr id="mwAZ8">
<td id="mwAaA" scope="row">41</td>
<td id="mwAaE">"<a href="https://en.wikipedia.org/wiki/Dynamite_(BTS_song)" id="mwAaI" rel="mw:WikiLink" title="Dynamite (BTS song)">Dynamite</a>"</td><td id="mwAaM"><a href="https://en.wikipedia.org/wiki/BTS" id="mwAaQ" rel="mw:WikiLink" title="BTS">BTS</a></td></tr>
<tr id="mwAaU">
<td id="mwAaY" scope="row">42</td>
<td id="mwAac">"<a href="https://en.wikipedia.org/wiki/Wockesha" id="mwAag" rel="mw:WikiLink" title="Wockesha">Wockesha</a>"</td><td id="mwAak"><a href="https://en.wikipedia.org/wiki/Moneybagg_Yo" id="mwAao" rel="mw:WikiLink" title="Moneybagg Yo">Moneybagg Yo</a></td></tr>
<tr id="mwAas">
<td id="mwAaw" scope="row">43</td>
<td id="mwAa0">"<a href="https://en.wikipedia.org/wiki/You_Right" id="mwAa4" rel="mw:WikiLink" title="You Right">You Right</a>"</td><td id="mwAa8"><a href="https://en.wikipedia.org/wiki/Doja_Cat" id="mwAbA" rel="mw:WikiLink" title="Doja Cat">Doja Cat</a> and <a href="https://en.wikipedia.org/wiki/The_Weeknd" id="mwAbE" rel="mw:WikiLink" title="The Weeknd">the Weeknd</a></td></tr>
<tr id="mwAbI">
<td id="mwAbM" scope="row">44</td>

In [2]:
rows = soup.find("table", class_="wikitable").find_all("tr")
sample_row = rows[1]
sample_row

<tr id="mwNg">
<td id="mwNw">1</td><td id="mwOA">"<a href="https://en.wikipedia.org/wiki/Candle_in_the_Wind_1997" id="mwOQ" rel="mw:WikiLink" title="Candle in the Wind 1997">Candle in the Wind 1997</a>" / "<a href="https://en.wikipedia.org/wiki/Something_About_the_Way_You_Look_Tonight" id="mwOg" rel="mw:WikiLink" title="Something About the Way You Look Tonight">Something About the Way You Look Tonight</a>"</td><td id="mwOw"><a href="https://en.wikipedia.org/wiki/Elton_John" id="mwPA" rel="mw:WikiLink" title="Elton John">Elton John</a></td></tr>

We can learn a lot from this sample row.  There are 3 entries - 1 per column, and they are rank, song title, and artist.
Entries 2 and 3 (song title and artist) have links.

In [3]:
# Scrape the content of each row
row_data = sample_row.find_all('td')
row_items = [item.get_text() for item in row_data]
row_items

['1',
 '"Candle in the Wind 1997" / "Something About the Way You Look Tonight"',
 'Elton John']

In [4]:
rank, song_title, artist_name = row_items
artist_name = artist_name.strip()   # there's a \n at its end we're removing
print(f'{song_title} by {artist_name} was ranked #{rank}.')

"Candle in the Wind 1997" / "Something About the Way You Look Tonight" by Elton John was ranked #1.

Next we will get the url links. Since occassionally there is more than one per artist and/or per song, we will store them in a list.

In [5]:
row_data[2]

In [6]:
row_data[2].find('a')

Use .attrs to extract the url text (see hint above).

In [7]:
[link['href'] for link in row_data[1].find_all('a')]

['https://en.wikipedia.org/wiki/Candle_in_the_Wind_1997',
 'https://en.wikipedia.org/wiki/Something_About_the_Way_You_Look_Tonight']

In [8]:
[link['href'] for link in row_data[2].find_all('a')]

['https://en.wikipedia.org/wiki/Elton_John']

In [9]:
[link['href'] for link in row_data[0].find_all('a')]

[]

In [10]:
song_urls = [link['href'] for link in row_data[1].find_all('a')]
artist_urls = [link['href'] for link in row_data[2].find_all('a')]
song_urls,artist_urls

(['https://en.wikipedia.org/wiki/Candle_in_the_Wind_1997',
  'https://en.wikipedia.org/wiki/Something_About_the_Way_You_Look_Tonight'],
 ['https://en.wikipedia.org/wiki/Elton_John'])

### Putting it all together
This creates a list of dictionaries for a year's worth of Billboard rows.  You pass it the year's rows and year value.  
Note that as the hint points out, some artist titles span 2 rows, so there is some code to catch and handle that.

In [11]:
def make_music_table(rows, year):
    music_table = []
    for entry_row in rows[1:]:   # start at 1; 0th is header
        row_data = entry_row.find_all('td')
        row_items = [item.get_text() for item in row_data]
        rank, song_title = row_items[:2]
        song_title = song_title.strip()
        song_urls = [link['href'] for link in row_data[1].find_all('a')]

        if len(row_items) == 3:
            artist_name = row_items[2]
            artist_urls = [link.attrs['href'] for link in row_data[2].find_all('a')]
        else:  # tries to catch an artist title spanning 2 rows (see Celine Dion in 1997)
            print(f'Rank {rank}. {song_title} spans 2 rows')  # diagnostic
            # artist_name will use the previous one
            # artist_urls will use the previous one
            pass
        artist_name = artist_name.strip()   # there's a \n at its end we're removing
        
        entry_dict = {'year':year, 'rank':rank, 'song title':song_title, 'artist_name(s)':artist_name,
                     'song_url(s)':song_urls, 'artist_url(s)':artist_urls}
        music_table.append(entry_dict)

        #print(f'{song_title} by {artist_name} was ranked #{rank}.')
    return music_table
music_table = make_music_table(rows, year)

Rank 50. "It's All Coming Back to Me Now" spans 2 rows

Display the first few:

In [12]:
music_table[:3]

[{'year': 1997,
  'rank': '1',
  'song title': '"Candle in the Wind 1997" / "Something About the Way You Look Tonight"',
  'artist_name(s)': 'Elton John',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Candle_in_the_Wind_1997',
   'https://en.wikipedia.org/wiki/Something_About_the_Way_You_Look_Tonight'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Elton_John']},
 {'year': 1997,
  'rank': '2',
  'song title': '"You Were Meant for Me" / "Foolish Games"',
  'artist_name(s)': 'Jewel',
  'song_url(s)': ['https://en.wikipedia.org/wiki/You_Were_Meant_for_Me_(Jewel_song)',
   'https://en.wikipedia.org/wiki/Foolish_Games'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Jewel_(singer)']},
 {'year': 1997,
  'rank': '3',
  'song title': '"I\'ll Be Missing You"',
  'artist_name(s)': 'Puff Daddy and Faith Evans featuring 112',
  'song_url(s)': ["https://en.wikipedia.org/wiki/I'll_Be_Missing_You"],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Sean_Combs',
   'https://en.wikipedia.org/wiki/Faith_Evans',
   'https://en.wikipedia.org/wiki/112_(band)']}]

and the last few entries:

In [13]:
music_table[-3:]

[{'year': 1997,
  'rank': '98',
  'song title': '"You\'re Makin\' Me High" / "Let It Flow"',
  'artist_name(s)': 'Toni Braxton',
  'song_url(s)': ["https://en.wikipedia.org/wiki/You're_Makin'_Me_High",
   'https://en.wikipedia.org/wiki/Let_It_Flow_(song)'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Toni_Braxton']},
 {'year': 1997,
  'rank': '99',
  'song title': '"You Must Love Me"',
  'artist_name(s)': 'Madonna',
  'song_url(s)': ['https://en.wikipedia.org/wiki/You_Must_Love_Me'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Madonna']},
 {'year': 1997,
  'rank': '100',
  'song title': '"Let It Go"',
  'artist_name(s)': 'Ray J',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Let_It_Go_(Ray_J_song)'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Ray_J']}]

In [14]:
import pandas as pd

In [15]:
# not required but let's see it as a data frame
music_df = pd.DataFrame(music_table)
music_df.head()

,year,rank,song title,artist_name(s),song_url(s),artist_url(s)
0,1997,1,"""Candle in the Wind 1997"" / ""Something About t...",Elton John,[https://en.wikipedia.org/wiki/Candle_in_the_W...,[https://en.wikipedia.org/wiki/Elton_John]
1,1997,2,"""You Were Meant for Me"" / ""Foolish Games""",Jewel,[https://en.wikipedia.org/wiki/You_Were_Meant_...,[https://en.wikipedia.org/wiki/Jewel_(singer)]
2,1997,3,"""I'll Be Missing You""",Puff Daddy and Faith Evans featuring 112,[https://en.wikipedia.org/wiki/I'll_Be_Missing...,"[https://en.wikipedia.org/wiki/Sean_Combs, htt..."
3,1997,4,"""Un-Break My Heart""",Toni Braxton,[https://en.wikipedia.org/wiki/Un-Break_My_Heart],[https://en.wikipedia.org/wiki/Toni_Braxton]
4,1997,5,"""Can't Nobody Hold Me Down""",Puff Daddy featuring Mase,[https://en.wikipedia.org/wiki/Can't_Nobody_Ho...,"[https://en.wikipedia.org/wiki/Sean_Combs, htt..."

## Part 3:  Scraping data for 2002-2021

Once you have been able to accomplish the task of scraping from the web into a list of dictionaries for 1997, you will now do the same for 2002-2021.  You should realize that you can use much of the same code you used above, surrounded by a loop...the only thing changing is the year at the end of the webpage address.  So in general, the Billboard Year end Hot 100 singles Wikipedia page is

https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_####


You should end up with a list (call it `multi_yr_table`) that holds 2000 dictionaries, one for each row (and each artist) that appears in the Billboard Top 100 over the past 20 years.  We will connect the url to the year as we loop through the year. The last few entries are (song URLs aren't required):

` [{'year': 2021,
  'rank': '98\n',
  'song title': '"Tombstone"',
  'artist_name(s)': 'Rod Wave',
  'song_url(s)': ['/wiki/Tombstone_(song)'],
  'artist_url(s)': ['/wiki/Rod_Wave']},
 {'year': 2021,
  'rank': '99\n',
  'song title': '"Drinkin\' Beer. Talkin\' God. Amen."',
  'artist_name(s)': 'Chase Rice featuring Florida Georgia Line',
  'song_url(s)': ['/wiki/Drinkin%27_Beer._Talkin%27_God._Amen.'],
  'artist_url(s)': ['/wiki/Chase_Rice', '/wiki/Florida_Georgia_Line']},
 {'year': 2021,
  'rank': '100\n',
  'song title': '"Todo de Ti"',
  'artist_name(s)': 'Rauw Alejandro',
  'song_url(s)': ['/wiki/Todo_de_Ti'],
  'artist_url(s)': ['/wiki/Rauw_Alejandro']}]`

In [16]:
multi_yr_table = []
for year in range(2002,2022):
    print(year, end = ' ') # diagnostic
    page = requests.get(BASE_URL + str(year),headers=headers)
    soup = BeautifulSoup(page.content, 'html.parser')
    rows = soup.find("table", class_="wikitable").find_all("tr")
    music_table = make_music_table(rows,year)
    multi_yr_table.append(music_table)
# Let's see an entry
multi_yr_table[3][5]

2002 2003 2004 2005 2006 2007 2008 Rank 10. "Forever" spans 2 rows
Rank 17. "Don't Stop the Music" spans 2 rows
2009 2010 2011 2012 Rank 17. "Whistle" spans 2 rows
2013 Rank 18. "Wrecking Ball" spans 2 rows
2014 2015 Rank 10. "The Hills" spans 2 rows
2016 Rank 2. "Sorry" spans 2 rows
Rank 21. "Heathens" spans 2 rows
2017 2018 2019 2020 2021

{'year': 2005,
 'rank': '6',
 'song title': '"Gold Digger"',
 'artist_name(s)': 'Kanye West featuring Jamie Foxx',
 'song_url(s)': ['https://en.wikipedia.org/wiki/Gold_Digger_(Kanye_West_song)'],
 'artist_url(s)': ['https://en.wikipedia.org/wiki/Kanye_West',
  'https://en.wikipedia.org/wiki/Jamie_Foxx']}

The last few:

In [17]:
multi_yr_table[-1][-3:]

[{'year': 2021,
  'rank': '98',
  'song title': '"Tombstone"',
  'artist_name(s)': 'Rod Wave',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Tombstone_(Rod_Wave_song)'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Rod_Wave']},
 {'year': 2021,
  'rank': '99',
  'song title': '"Drinkin\' Beer. Talkin\' God. Amen."',
  'artist_name(s)': 'Chase Rice featuring Florida Georgia Line',
  'song_url(s)': ["https://en.wikipedia.org/wiki/Drinkin'_Beer._Talkin'_God._Amen."],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Chase_Rice',
   'https://en.wikipedia.org/wiki/Florida_Georgia_Line']},
 {'year': 2021,
  'rank': '100',
  'song title': '"Todo de Ti"',
  'artist_name(s)': 'Rauw Alejandro',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Todo_de_Ti'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Rauw_Alejandro']}]

In [18]:
len(multi_yr_table)

20

In [19]:
# Let's create a flattened table to convert to a pandas data frame
flat_table = [item for yr_table in multi_yr_table for item in yr_table]

In [20]:
len(flat_table)

2000

In [21]:
flat_table[:3]

[{'year': 2002,
  'rank': '1',
  'song title': '"How You Remind Me"',
  'artist_name(s)': 'Nickelback',
  'song_url(s)': ['https://en.wikipedia.org/wiki/How_You_Remind_Me'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Nickelback']},
 {'year': 2002,
  'rank': '2',
  'song title': '"Foolish"',
  'artist_name(s)': 'Ashanti',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Foolish_(Ashanti_song)'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Ashanti_(singer)']},
 {'year': 2002,
  'rank': '3',
  'song title': '"Hot in Herre"',
  'artist_name(s)': 'Nelly',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Hot_in_Herre'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Nelly']}]

In [22]:
flat_table[-3:]

[{'year': 2021,
  'rank': '98',
  'song title': '"Tombstone"',
  'artist_name(s)': 'Rod Wave',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Tombstone_(Rod_Wave_song)'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Rod_Wave']},
 {'year': 2021,
  'rank': '99',
  'song title': '"Drinkin\' Beer. Talkin\' God. Amen."',
  'artist_name(s)': 'Chase Rice featuring Florida Georgia Line',
  'song_url(s)': ["https://en.wikipedia.org/wiki/Drinkin'_Beer._Talkin'_God._Amen."],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Chase_Rice',
   'https://en.wikipedia.org/wiki/Florida_Georgia_Line']},
 {'year': 2021,
  'rank': '100',
  'song title': '"Todo de Ti"',
  'artist_name(s)': 'Rauw Alejandro',
  'song_url(s)': ['https://en.wikipedia.org/wiki/Todo_de_Ti'],
  'artist_url(s)': ['https://en.wikipedia.org/wiki/Rauw_Alejandro']}]

In [23]:
len(flat_table)

2000

Finally, convert this table to a pandas dataframe.
You don't need to do any analysis but note that if you've done this correctly, you will have scraped 2000 records from 20 different web pages into one dataframe to which  all of the pandas tools and techniques we have learned can be applied.

In [24]:
multi_yr_df = pd.DataFrame(flat_table)

multi_yr_df

,year,rank,song title,artist_name(s),song_url(s),artist_url(s)
0,2002,1,"""How You Remind Me""",Nickelback,[https://en.wikipedia.org/wiki/How_You_Remind_Me],[https://en.wikipedia.org/wiki/Nickelback]
1,2002,2,"""Foolish""",Ashanti,[https://en.wikipedia.org/wiki/Foolish_(Ashant...,[https://en.wikipedia.org/wiki/Ashanti_(singer)]
2,2002,3,"""Hot in Herre""",Nelly,[https://en.wikipedia.org/wiki/Hot_in_Herre],[https://en.wikipedia.org/wiki/Nelly]
3,2002,4,"""Dilemma""",Nelly featuring Kelly Rowland,[https://en.wikipedia.org/wiki/Dilemma_(Nelly_...,"[https://en.wikipedia.org/wiki/Nelly, https://..."
4,2002,5,"""Wherever You Will Go""",The Calling,[https://en.wikipedia.org/wiki/Wherever_You_Wi...,[https://en.wikipedia.org/wiki/The_Calling_(ba...
...,...,...,...,...,...,...
1995,2021,96,"""Things a Man Oughta Know""",Lainey Wilson,[https://en.wikipedia.org/wiki/Things_a_Man_Ou...,[https://en.wikipedia.org/wiki/Lainey_Wilson]
1996,2021,97,"""Throat Baby (Go Baby)""",BRS Kash,[https://en.wikipedia.org/wiki/Throat_Baby_(Go...,[https://en.wikipedia.org/wiki/BRS_Kash]
1997,2021,98,"""Tombstone""",Rod Wave,[https://en.wikipedia.org/wiki/Tombstone_(Rod_...,[https://en.wikipedia.org/wiki/Rod_Wave]
1998,2021,99,"""Drinkin' Beer. Talkin' God. Amen.""",Chase Rice featuring Florida Georgia Line,[https://en.wikipedia.org/wiki/Drinkin'_Beer._...,"[https://en.wikipedia.org/wiki/Chase_Rice, htt..."
1999,2021,100,"""Todo de Ti""",Rauw Alejandro,[https://en.wikipedia.org/wiki/Todo_de_Ti],[https://en.wikipedia.org/wiki/Rauw_Alejandro]

In [25]:
# not required...
multi_yr_df['artist_name(s)'].value_counts()

artist_name(s)
Taylor Swift                                 24
Rihanna                                      21
Drake                                        19
Kelly Clarkson                               17
Pink                                         15
                                             ..
Cole Swindell                                 1
Lainey Wilson                                 1
BRS Kash                                      1
Chase Rice featuring Florida Georgia Line     1
Rauw Alejandro                                1
Name: count, Length: 1141, dtype: int64